language: c
before_install:
  - sudo apt-get install build-essential
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install libc6-i386
  - wget http://download.labs.mediatek.com/LinkIt_SDK_V4.2.0_travis.tar.gz
install:
  - tar --keep-old-files -zxvf LinkIt_SDK_V4.2.0_travis.tar.gz -C .
script:
  - cd project/linkit_7697/apps/arduino/arduino_lib/GCC/
  - make
  - cd -
  - mkdir out
  - ./mk_ide_pkg.pl -o out -v 0.0.1

notifications:
  email:
    on_success: change
    on_failure: change